name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false

      matrix:
        platform:
          - { os: ubuntu-latest }
          - { os: windows-latest }
          - { os: macos-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Bls tests
        run: cargo test -release --features=bls